import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Page.module.scss";
import axios from "axios";
import { Form, Button } from "react-bootstrap";
import QuestionSection from "@/components/QuestionSection/QuestionSection";

const Hulp: NextPage = () => {
  const [subject, setSubject] = React.useState<string | undefined>();
  const [timeframe, setTimeframe] = React.useState<string | undefined>();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;600&family=Roboto:wght@300;400;500;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main id={styles.main}>
        <div className={styles.container}>
          <div style={{ color: "#AAA" }}>
            <span style={{ fontWeight: 600, color: "rgba(102, 204, 255, 1)" }}>
              VaCiD
            </span>{" "}
            | Ik zit ergens mee
          </div>
          <h2
            style={{
              marginTop: 50,
              marginBottom: 20,
              marginLeft: -30,
              fontSize: 54,
              fontWeight: 500,
              color: "#666",
              fontFamily: `"Roboto", sans-serif`,
            }}
          >
            Wat goed dat je hier bent
          </h2>
          <div style={{ maxWidth: 600, marginBottom: 50 }}>
            Wij helpen je graag verder in de situatie waar je mee zit. Om je
            beter te begrijpen hebben we hieronder twee vragen voor je.
          </div>
          <QuestionSection
            question={"1. Over wie gaat het?"}
            options={[
              { text: "Het gaat over mijzelf", name: "self" },
              { text: "Ik zag iets gebeuren", name: "other" },
            ]}
            selected={subject}
            setSelected={setSubject}
          />
          <QuestionSection
            question={"2. Hoe kort geleden is dit gebeurd?"}
            options={[
              { text: "Minder dan 7 dagen geleden", name: "recent" },
              { text: "Meer dan 7 dagen geleden", name: "past" },
            ]}
            selected={timeframe}
            setSelected={setTimeframe}
          />
          <h3
            style={{
              marginTop: 20,
              marginBottom: 30,
              marginLeft: -15,
              fontSize: 34,
              fontWeight: 500,
              color: "#666",
              fontFamily: `"Roboto", sans-serif`,
            }}
          >
            Ons advies
          </h3>
          <p>
            Omdat je situatie zich kort geleden heeft afgespeeld kunnen
            professionele hulpdiensten jou met voorrang helpen. Als zich een
            heftige gebeurtenis heeft afgespeeld, dan kun je direct met hen
            contact opnemen. Als het gaat om seksueel overschrijdend gedrag, dan
            raden wij aan om te rade te gaan bij het Centrum Seksueel Geweld.
            Zij kunnen geheel vrijblijvend en vertrouwelijk advies leveren bij
            jouw situatie.
          </p>
          <p>Nog meer tekst en uitleg</p>

          <h4
            style={{
              marginTop: 20,
              marginBottom: 30,
              fontSize: 24,
              fontWeight: 500,
              color: "#666",
              fontFamily: `"Roboto", sans-serif`,
            }}
          >
            Contact opnemen
          </h4>
          <Form style={{ paddingBottom: 150 }}>
            <Form.Group className="mb-3" controlId="formName">
              <Form.Label>Naam</Form.Label>
              <Form.Control type="text" placeholder="Voer je naam in" />
              <Form.Text className="text-muted">
                Lees hier waarom wij geen anonieme klachten behandelen
              </Form.Text>
            </Form.Group>

            <Form.Group className="mb-3" controlId="formEmail">
              <Form.Label>Email</Form.Label>
              <Form.Control type="password" placeholder="Password" />
            </Form.Group>
            <Form.Group className="mb-3" controlId="formBasicCheckbox">
              <Form.Check type="checkbox" label="Check me out" />
            </Form.Group>
            <Button
              variant="primary"
              type="submit"
              onClick={(e) => {
                axios
                  .post("/api/email", {
                    firstName: "Fred",
                    lastName: "Flintstone",
                  })
                  .then(function (response) {
                    console.log(response);
                  })
                  .catch(function (error) {
                    console.log(error);
                  });
              }}
            >
              Submit
            </Button>
          </Form>
        </div>
      </main>
    </div>
  );
};

export default Hulp;
