import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Page.module.scss";
import axios from "axios";
import { FloatingLabel, Form, Button, Accordion } from "react-bootstrap";
import QuestionSection from "@/components/QuestionSection/QuestionSection";

const Hulp: NextPage = () => {
  const [subject, setSubject] = React.useState<string | undefined>();
  const [timeframe, setTimeframe] = React.useState<string | undefined>();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;600&family=Roboto:wght@300;400;500;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main id={styles.main}>
        <div className={styles.container}>
          <div style={{ color: "#AAA" }}>
            <span style={{ fontWeight: 600, color: "rgba(102, 204, 255, 1)" }}>
              VaCiD
            </span>{" "}
            | Ik zit ergens mee
          </div>
          <h2
            style={{
              marginTop: 50,
              marginBottom: 20,
              marginLeft: -30,
              fontSize: 54,
              fontWeight: 500,
              color: "#666",
              fontFamily: `"Roboto", sans-serif`,
            }}
          >
            Wat goed dat je hier bent
          </h2>
          <div style={{ maxWidth: 600, marginBottom: 50 }}>
            Wij helpen je graag verder in de situatie waar je mee zit. Om je
            beter te begrijpen hebben we hieronder twee vragen voor je.
          </div>
          <QuestionSection
            question={"1. Over wie gaat het?"}
            options={[
              { text: "Het gaat over mijzelf", name: "self" },
              { text: "Ik zag iets gebeuren", name: "other" },
            ]}
            selected={subject}
            setSelected={setSubject}
          />
          <QuestionSection
            question={"2. Hoe kort geleden is dit gebeurd?"}
            options={[
              { text: "Minder dan 7 dagen geleden", name: "recent" },
              { text: "Meer dan 7 dagen geleden", name: "past" },
            ]}
            selected={timeframe}
            setSelected={setTimeframe}
          />
          <h3
            style={{
              marginTop: 20,
              marginBottom: 30,
              marginLeft: -15,
              fontSize: 34,
              fontWeight: 500,
              color: "#666",
              fontFamily: `"Roboto", sans-serif`,
            }}
          >
            Ons advies
          </h3>
          <p>
            Omdat je situatie zich kort geleden heeft afgespeeld kunnen
            professionele hulpdiensten jou met voorrang helpen. Als zich een
            heftige gebeurtenis heeft afgespeeld, dan kun je direct met hen
            contact opnemen. Achteraf horen wij alsnog van je verhaal, zodat we
            er binnen de danswereld rekening mee kunnen houden.
          </p>
          <Accordion style={{ margin: "30px 0" }}>
            <Accordion.Item eventKey="0">
              <Accordion.Header>
                Professionele hulp bij seksueel overschrijdend gedrag
              </Accordion.Header>
              <Accordion.Body>
                <p>
                  Als het gaat om seksueel overschrijdend gedrag, dan raden wij
                  aan om te rade te gaan bij het Centrum Seksueel Geweld. Zij
                  kunnen geheel vrijblijvend en vertrouwelijk advies leveren bij
                  jouw situatie. Ook geven zij op hun website al veel bruikbare
                  voorlichting om seksueel overschrijdend gedrag beter te kunnen
                  begrijpen.
                </p>
                <p>
                  <a
                    href="https://centrumseksueelgeweld.nl/"
                    rel="noopener noreferrer nofollow"
                  >
                    &#8250; Klik hier om naar de website van CSG te gaan
                  </a>
                </p>
                <p>
                  Twijfel niet in het geval van fysiek seksueel geweld en neem
                  direct contact op met de politie. Zij hebben een speciale
                  afdeling, de zedenpolitie, die speciaal is ingericht om je te
                  ondersteunen.
                </p>
                <p>
                  Je kunt hiervoor de politie bellen op 0900-8844 en vragen naar
                  de afdeling zedendelicten.
                </p>
              </Accordion.Body>
            </Accordion.Item>
            <Accordion.Item eventKey="1">
              <Accordion.Header>
                Neem bij twijfel altijd contact op
              </Accordion.Header>
              <Accordion.Body>
                Slachtoffers blijven vaak met een schuldgevoel zitten na een
                vervelende situatie. Het is daarom belangrijk voor het
                verwerkingsproces om er met een vertrouwd persoon over te
                praten. Je kan altijd bij ons terecht voor een oriënterend
                gesprek en wij zullen daar van onze kant nooit iets mee doen
                voordat jij daar toestemming voor geeft.
              </Accordion.Body>
            </Accordion.Item>
            <Accordion.Item eventKey="2">
              <Accordion.Header>
                Hoe zit het met geheimhouding?
              </Accordion.Header>
              <Accordion.Body>
                <p>
                  Onze vertrouwenspersonen werken onder geheimhoudingsplicht.
                  Mocht je het toch fijner vinden om iemand buiten de danswereld
                  te spreken over gevoelige en persoonlijke gebeurtenissen, dan
                  kun je ook direct contact opnemen met één van de aangesloten
                  hulporganisaties.
                </p>
                <p>
                  Wij horen uiteindelijk graag je verhaal, zodat we je ervaring
                  als signalement kunnen gebruiken om een beter beleid te vormen
                  in de danswereld. Met jouw melding maken we de dansvloer
                  veiliger en leuker voor iedereen.
                </p>
              </Accordion.Body>
            </Accordion.Item>
            <Accordion.Item eventKey="3">
              <Accordion.Header>
                Kan ik mijn klacht ook anoniem indienen?
              </Accordion.Header>
              <Accordion.Body>
                <p>
                  Nee. Om zuiver op te kunnen handelen bij misstanden vinden wij
                  het belangrijk dat dit niet anoniem gebeurt. Dat maakt ons
                  minder kwetsbaar voor smaad en laster.
                </p>
                <p>
                  Al je gegevens blijven wel ten alle tijde beschermd bij ons.
                  Dat houdt in dat wij de gegevens over je melding nooit met
                  derden zullen delen als jij dat niet wil.
                </p>
              </Accordion.Body>
            </Accordion.Item>
          </Accordion>

          <h4
            style={{
              marginTop: 20,
              marginBottom: 30,
              fontSize: 24,
              fontWeight: 500,
              color: "#666",
              fontFamily: `"Roboto", sans-serif`,
            }}
          >
            Contact opnemen
          </h4>
          <p>
            Wij staan voor je klaar om je te helpen. Als je contact opneemt met
            ons dan komt één van onze vertrouwenspersonen binnen 7 dagen bij je
            terug. Daarna kijken we samen wat de beste vervolgstappen zijn in
            jouw situatie.
          </p>
          <p>
            Deze informatie blijft altijd van jou. Daarmee bedoelen we jouw
            verhaal niet naar komt of gedeeld zal worden zonder jouw
            toestemming. Wij ondernemen dan ook geen actie zonder jou daar eerst
            in te betrekken.
          </p>
          <Form style={{ marginTop: 20, paddingBottom: 150 }}>
            <Form.Group className="mb-3" controlId="formName">
              <Form.Label>Naam</Form.Label>
              <Form.Control type="text" placeholder="Voer je naam in" />
            </Form.Group>

            <Form.Group className="mb-3" controlId="formEmail">
              <Form.Label>Email</Form.Label>
              <Form.Control type="email" placeholder="Voer je email in" />
            </Form.Group>
            <FloatingLabel
              controlId="floatingTextarea2"
              label="Bericht"
              style={{ margin: "30px 0" }}
            >
              <Form.Control
                as="textarea"
                placeholder="Leave a comment here"
                style={{ minHeight: 200 }}
              />
            </FloatingLabel>
            <Button
              variant="outline-secondary"
              type="submit"
              onClick={(e) => {
                axios
                  .post("/api/email", {
                    firstName: "Fred",
                    lastName: "Flintstone",
                  })
                  .then(function (response) {
                    console.log(response);
                  })
                  .catch(function (error) {
                    console.log(error);
                  });
              }}
            >
              Bericht versturen
            </Button>
          </Form>
        </div>
      </main>
    </div>
  );
};

export default Hulp;
