import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import logo from "@/images/logo.png";
import dancingPeople from "@/images/dancing-people.jpg";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;600&family=Roboto:wght@300;400;900&display=swap"
          rel="stylesheet"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header id={styles.header}>header</header>

      <main id={styles.main}>
        <div className={styles.container}>
          <div style={{ width: "58%" }}>
            <Image
              src={logo}
              alt="Picture of the author"
              width={689}
              height={242}
            />
            <div style={{ margin: "80px 50px" }}>
              <h2 style={{ marginBottom: 30, color: "#9062CC" }}>
                Violence and Complaints in Dance
              </h2>
              <p>
                VaCiD is in het leven geroepen om dansen vrij en vooral veilig
                te maken. Als meldpunt voor grensoverschrijdend gedrag
                ondersteunen wij in de afhandeling daarvan. Je kunt bij ons of
                via ons terecht met vragen of meldingen over de danswereld.
              </p>
            </div>
            <div
              style={{
                position: "relative",
                display: "flex",
                justifyContent: "space-between",
                marginRight: -120,
                zIndex: 1,
              }}
            >
              <div
                style={{
                  width: 350,
                  height: 140,
                  boxShadow: "3px 3px 10px rgba(0,0,0,0.15)",
                  background: "#fff",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontFamily: "Roboto",
                  fontSize: 20,
                  fontWeight: 400,
                  borderRadius: 5,
                  paddingRight: 75,
                }}
              >
                <div
                  style={{ borderBottom: "3px solid rgb(255, 153, 102, 0.5)" }}
                >
                  Ik zit ergens mee
                </div>
              </div>
              <div
                style={{
                  width: 350,
                  height: 140,
                  boxShadow: "3px 3px 10px rgba(0,0,0,0.15)",
                  background: "#fff",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontFamily: "Roboto",
                  fontSize: 20,
                  fontWeight: 400,
                  borderRadius: 5,
                  paddingRight: 75,
                }}
              >
                <div
                  style={{ borderBottom: "3px solid rgb(102, 204, 255, 0.5)" }}
                >
                  Ik zoek informatie
                </div>
              </div>
            </div>
          </div>
          <div style={{ width: "42%" }}>
            <div style={{ padding: "60px 0 0 40px" }}>
              <Image
                src={dancingPeople}
                alt="Picture of the author"
                width={750}
                height={1072}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
