import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Page.module.scss";
import ContactForm from "@/components/ContactForm/ContactForm";

const Hulp: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;600&family=Roboto:wght@300;400;500;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main id={styles.main}>
        <div className={styles.container}>
          <div style={{ color: "#AAA" }}>
            <span style={{ fontWeight: 600, color: "rgba(102, 204, 255, 1)" }}>
              VaCiD
            </span>{" "}
            | Ik zoek informatie
          </div>
          <h2 className={styles.pageTitle}>Stel hier je vraag</h2>
          <div style={{ maxWidth: 600 }}>
            We zijn net begonnen als initiatief en begrijpen dat er nog veel
            vragen over ons bestaan en handelswijze zijn. Terwijl we werken aan
            de correcte informatievoorziening kun je alvast bij ons terecht via
            het onderstaande formulier.
          </div>

          <ContactForm show />
        </div>
      </main>
    </div>
  );
};

export default Hulp;
